### ISSUE TITLE
Task List - v0.02

### ISSUE THREAD

**Issue by LucasBN** [LucasBN/FearlessAthletes#2]
- [ ] Being able to select exercises to group them into workouts
- [ ] Store the intakes of each macro in user defaults
- [ ] Redesign menus
- [ ] Filter exercise list automatically

**Comment by LucasBN** [comment]
-[] Update tasks for v0.03

**Comment by LucasBN** [comment]
- [ ] Complete v0.03
